const FETCH_TODOS = "FETCH_TODOS";
const ADD_TODO = "ADD_TODO";
const TODO_VIEW_MODE = "TODO_VIEW_MODE";
const DELETE_TODO = "DELETE_TODO";
const EDIT_TODO = "EDIT_TODO";
const TOGGLE_TODO_DONE = "TOGGLE_TODO_DONE";
const DIALOG_ACTION = "DIALOG_ACTION";
const OPEN_DIALOG = "OPEN_DIALOG";
const OPEN_EDIT_DIALOG = "OPEN_EDIT_DIALOG";
const EDIT_DIALOG_ACTION = "EDIT_DIALOG_ACTION";
const FETCH_CATEGORIES = "FETCH_CATEGORIES";
const DIALOG_EDIT_TODO = "DIALOG_EDIT_TODO";

export {
  FETCH_TODOS,
  ADD_TODO,
  TODO_VIEW_MODE,
  DELETE_TODO,
  EDIT_TODO,
  TOGGLE_TODO_DONE,
  DIALOG_ACTION,
  OPEN_DIALOG,
  OPEN_EDIT_DIALOG,
  EDIT_DIALOG_ACTION,
  FETCH_CATEGORIES,
  DIALOG_EDIT_TODO
};
